name: Test Build
on: [push]
jobs:
  Use-Action:
    name: Use Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          path: start-ipfs-daemon-action
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
      - uses: actions/checkout@v6
        with:
          repository: ipfs/kubo
          path: kubo
      - run: |
          make build
          make install
        working-directory: kubo
        shell: bash
      - uses: ./start-ipfs-daemon-action
